# Generated by Django 5.2.8 on 2026-04-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
    ]
